services:
  portfolio_a:
    image: portfolio_a
    container_name: portfolio_a
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    restart: unless-stopped
    environment:
      - TG_TOKEN=${TG_TOKEN}
      - TG_CHAT=${TG_CHAT}

  portfolio_b:
    image: portfolio_b
    container_name: portfolio_b
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    restart: unless-stopped
    environment:
      - TG_TOKEN=${TG_TOKEN}
      - TG_CHAT=${TG_CHAT}
