export const codePool = [
    '<42 className="universe">',
    '<ShrodingerCat>...</ShrodingerCat>',
    '<BigBang />',
    '<RocketToMars />',
    '<CoffeeCup className="hot" />',
    '<HelloWorld>42</HelloWorld>',
    '<AI className="confused" />',
    '<QuantumLeaps />',
    '<debugMode on />',
    '<CSSMagic />',
    '<JS_is_fun />',
    '<TimeMachine />',
    '<BugHunter />',
    '<404PageNotFound />',
    '<InfiniteLoop />',
    '<RandomFunction />',
    '<NullPointer />',
    '<ConsoleBanana />',
    '<ReactRocks />',
    '<UseEffectForever />',
    '<AsyncAwait />',
    '<HoverMe />',
    '<TailwindFTW />',
    '<DarkModeOn />',
    '<LightModeOff />',
    '<HTMLIpsum />',
    '<CSSWizard />',
    '<JSConfetti />',
    '<BinaryUnicorn />',
    '<CoffeeOverflow />',
    '<CodeIsLife />',
    '<Teleport />',
    '<VirtualReality />',
    '<Error404 />',
    '<StackOverflow />',
    '<CompileTime />',
    '<RuntimeError />',
    '<Debugger />',
    '<PromiseAll />',
    '<MemoryLeak />',
    '<UndefinedVariable />',
    '<HelloUniverse />',
];

export function getRandomSnippets(pool: string[], count: number) {
    const shuffled = pool.sort(() => 0.5 - Math.random());
    return shuffled.slice(0, count).join(" ");
}